services:
  postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
      ports:
        - 5432:5432
volumes:
  postgres-db-volume: